services:
  - type: web
    name: pdf-converter
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PYTHONUNBUFFERED
        value: 1 