services:
  - type: web
    name: pdf-converter
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev poppler-utils libgl1 libglib2.0-0
      pip install -r requirements-render.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 