services:
  - type: web
    name: pdf-converter
    env: python
    plan: free
    buildCommand: pip install -r requirements-vercel.txt
    startCommand: uvicorn api.index:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 